spring:
  batch:
    job:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:templates/
  h2:
    console:
      path: /h2-console
      enabled: true
file:
  extensions: .java,.html,.css,.jsp,.xml,.properties
  targetFolderName: gitProjects
  excludedFolder: src\test,out,gradle,build,.idea,.gradle,.git
server:
  error:
    path: /error
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG